class Localization:
    def __init__(self):
        self.data = {
            'loginError': '', 
            'loginButton': '', 
            'rememberMe': '', 
            'email': '', 
            'password': '', 
            'loginChangePassword': '', 
            'loginPageSlogan':'', 
            'loginAddNewAccount':'',
            'languageSelectBoxLabel': '',
            'firstName': '',
            'lastName': '',
            'passwordRepeated': '',
            'registerButton': '',
			'birthdate': '',
			'confirmationSuccess': '',
			'confirmationFailure': '',
			'registrationSuccess': '',
			'registrationError': '',
			'serverUnaviable': '',
			'changePasswordButton': '',
			'changePasswordInfo': '',
			'changePasswordCodeGenerationInfo': '',
			'changePasswordSuccess': '',
			'changePasswordFailure':'',
			'codeGenerationSuccess': '',
			'codeGenerationFailure': '',
            'topMenuProfile': '',
            'topMenuFind': '',
            'topMenuConversation': '',
            'logout': ''
        }
   