USE talk_to_me;

DROP TABLE `localization`;

CREATE TABLE `localization` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `localization` varchar(10) NOT NULL,
  `fieldName` varchar(45) NOT NULL,
  `value` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `talk_to_me`.`localization`
	(`localization`, `fieldName`, `value`)
VALUES
	('pl-pl', 'languageName', 'Polski'),
	('en-us', 'languageName', 'English'),
	('pl-pl', 'loginError', 'Podałeś nieprawidłowe dane!'),
	('en-us', 'loginError', 'You have entered wrong credentials!'),
    ('pl-pl', 'loginButton', 'Zaloguj'),
	('en-us', 'loginButton', 'Login'),
    ('pl-pl', 'rememberMe', 'Zapamiętaj mnie'),
	('en-us', 'rememberMe', 'Remember me'),
    ('pl-pl', 'email', 'Email'),
	('en-us', 'email', 'Email'),
    ('pl-pl', 'password', 'Hasło'),
	('en-us', 'password', 'Password'),
    ('pl-pl', 'loginChangePassword', 'Nie pamiętasz hasła?'),
	('en-us', 'loginChangePassword', 'Forgot your password?'),
    ('pl-pl', 'loginPageSlogan', 'Poznaj nowych przyjaciół z całego świata!'),
	('en-us', 'loginPageSlogan', 'Meet new friends from all around of the world!'),
    ('pl-pl', 'loginAddNewAccount', 'Załóż nowe konto'),
	('en-us', 'loginAddNewAccount', 'Create a new account'),
	('pl-pl', 'languageSelectBoxLabel', 'Zmień język'),
	('en-us', 'languageSelectBoxLabel', 'Change language'),
	('pl-pl', 'firstName', 'Imię'),
	('en-us', 'firstName', 'First name'),
	('pl-pl', 'lastName', 'Nazwisko'),
	('en-us', 'lastName', 'Last name'),
	('pl-pl', 'passwordRepeated', 'Powtórz hasło'),
	('en-us', 'passwordRepeated', 'Repeat password'),
	('pl-pl', 'registerButton', 'Zarejestruj'),
	('en-us', 'registerButton', 'Register'),
	('pl-pl', 'registrationError', 'Już istnieje użytkownik o tym adresie email!'),
	('en-us', 'registrationError', 'User for given address email already exist!'),
	('pl-pl', 'serverUnaviable', 'Nie można połączyć się z serwerem, spróbuj ponownie póniej.'),
	('en-us', 'serverUnaviable', 'Cannot connect to remote server, please try again later.'),
	('pl-pl', 'birthdate', 'Data urodzenia'),
	('en-us', 'birthdate', 'Birth date'),
	('pl-pl', 'confirmationSuccess', 'Twoja rejestracja została potwierdzona!'),
	('en-us', 'confirmationSuccess', 'Your registration was confirmed!'),
	('pl-pl', 'confirmationFailure', 'Twoja rejestracja została już potwierdzona lub link potwierdzający wygasł! W razie wygaśnięcia linku, zarejestruj się ponownie.'),
	('en-us', 'confirmationFailure', 'Your registration is already confirmed or confirmation link expired! If your confirmation linki expired you need to register again.'),
	('pl-pl', 'confirmationEmail', 'Dziękujemy za rejestracje w serwisie TalkToMe!\nŻeby potwierdzić swoją rejestrację kliknij w poniższy link:\n\n%s\n\nJeżeli nie rejestrowałeś się w naszym portalu to zignoruj ten email.'),
	('en-us', 'confirmationEmail', 'Thank you for your registration in TalkToMe!\nTo confirm your registration click below link:\n\n%s\n\nIf you have not registered in our service then ignore this email.'),
	('pl-pl', 'registrationSuccess', 'Rejestracja powiodła się! Przejdź do swojej skrzynki pocztowej i potwierdź rejestracje.'),
	('en-us', 'registrationSuccess', 'Registration succeeded!! Go to your mail box and confirm your registration.'),
	('pl-pl', 'confirmationEmailSubject', 'Potwierdzenie rejestracji'),
	('en-us', 'confirmationEmailSubject', 'Confirmation of registration'),
	('pl-pl', 'changePasswordButton', 'Zmień'),
	('en-us', 'changePasswordButton', 'Change'),
	('pl-pl', 'changePasswordEmail', 'Aby zmienić hasło kliknij na poniższy link:\n\n%s\n\nJeśli nie chcesz zmieniać hasła zignoruj tę wiadomość.'),
	('en-us', 'changePasswordEmail', 'To change password clik link below:\n\n%s\n\nIf you are no longer intrested in changing password then ignore this message.'),
	('pl-pl', 'changePasswordEmailSubject', 'Zmiana hasła'),
	('en-us', 'changePasswordEmailSubject', 'Change password'),
	('pl-pl', 'changePasswordCodeGenerationInfo', 'Podaj adres email którego użyłeś podczas rejestracji:'),
	('en-us', 'changePasswordCodeGenerationInfo', 'Insert email address which was used during registration:'),
	('pl-pl', 'changePasswordInfo', 'Podaj nowe hasło:'),
	('en-us', 'changePasswordInfo', 'Insert new password:'),
	('pl-pl', 'changePasswordSuccess', 'Hasło zostało zmienione! Zachwile zostaniesz przekierowany do strony logowania.'),
	('en-us', 'changePasswordSuccess', 'Password has changed! In few seconds you will be redirected to login page.'),
	('pl-pl', 'changePasswordFailure', 'Zmiana hasła nie powiodłą się, spróbuj ponownie pónźiej'),
	('en-us', 'changePasswordFailure', 'Changing password failed, try again later.'),
	('pl-pl', 'codeGenerationSuccess', 'Link do zmiany hasła został wysłany na twóją skrzynke pocztową.'),
	('en-us', 'codeGenerationSuccess', 'Link for changing password was sent to your email box.'),
	('pl-pl', 'codeGenerationFailure', 'Generowanie linku do zmiany hasła nie powiodło się, spróbuj ponownie póniej.'),
	('en-us', 'codeGenerationFailure', 'Generating link for password change failed, try again later.'),
	('pl-pl', 'topMenuProfile', 'Profil'),
	('en-us', 'topMenuProfile', 'Profile'),
	('pl-pl', 'topMenuFind', 'Szukaj znajomych'),
	('en-us', 'topMenuFind', 'Find firends'),
	('pl-pl', 'topMenuConversation', 'Rozmowa'),
	('en-us', 'topMenuConversation', 'Conversation'),
	('pl-pl', 'logout', 'Wyloguj'),
	('en-us', 'logout', 'Logout');